Repository hack-ink/subalfred, pull requests merged in 2022-10, with the labels that each got.

#181 Document `subcryptor`
  src/subalfred/core/error/mod.rs
  substrate-minimal/subcryptor/src/error.rs
  substrate-minimal/subcryptor/src/lib.rs
Labels: Doc

#209 Features check doc
  doc/src/user/cli/check.md
  doc/src/user/cli/state.md
Labels: Doc

#212 Use `cargo-nextest` for testing
  .github/workflows/checks.yml
  .github/workflows/release.yml
  .github/workflows/staging.yml
  rust-toolchain.toml
Labels: CI/CD

#215 Improve log doc
  src/bin/subalfred/cli.rs
Labels: Doc

#217 Always use latest version
  doc/src/user/installation.md
Labels: Doc

#224 Clean features
  bin/subalfred/Cargo.toml
  lib/core/Cargo.toml
Labels: Cc

#223 State command example
  Cargo.lock
  Cargo.toml
  examples/Cargo.lock
  examples/Cargo.toml
  examples/members/state/Cargo.toml
  examples/members/state/src/main.rs
  examples/state/src/main.rs
  examples/util/Cargo.toml
  examples/util/src/lib.rs
  lib/core/src/cargo/test.rs
Labels: Doc

#228 Typo & formatting
  doc/src/user/cli/convert.md
  doc/src/user/cli/get.md
  doc/src/user/cli/storage-key.md
Labels: Doc

#234 update maths expression
  doc/src/user/cli/get.md
Labels: Doc

#236 Setup toolchain based on `rust-toolchain.toml`
  .github/workflows/checks.yml
  .github/workflows/release.yml
  .github/workflows/staging.yml
Labels: CI/CD

#238 Skip checking `[dev-dependencies]` features
  lib/core/src/check/features/mock-runtime/Cargo.toml
  lib/core/src/check/features/mod.rs
Labels: Core

#240 Tracing log testing
  Cargo.lock
  lib/util/Cargo.toml
  lib/util/src/lib.rs
Labels: TI

#242 Update get.md
  doc/src/user/cli/get.md
Labels: Doc

#241 Rewrite `subrpcer` & doc some crates
  Cargo.lock
  Cargo.toml
  README.md
  bin/subalfred/Cargo.toml
  bin/subalfred/src/command/check/runtime.rs
  bin/subalfred/src/command/convert/ascii2hex.rs
  bin/subalfred/src/command/convert/bytes2hex.rs
  bin/subalfred/src/command/convert/bytes_style.rs
  bin/subalfred/src/command/convert/hex2bytes.rs
  bin/subalfred/src/command/impl/Cargo.toml
  bin/subalfred/src/command/storage_key.rs
  bin/subalfred/src/main.rs
  lib/core/Cargo.toml
  lib/core/src/cargo/mod.rs
  lib/core/src/cargo/test.rs
  lib/core/src/http/mod.rs
  lib/core/src/jsonrpc/http/test.rs
  lib/core/src/jsonrpc/mod.rs
  lib/core/src/jsonrpc/ws/mod.rs
  lib/core/src/node/mod.rs
  lib/core/src/ss58/mod.rs
  lib/core/src/state/diff.rs
  lib/core/src/state/fork_off.rs
  lib/core/src/state/mod.rs
  lib/core/src/substrate_client/mod.rs
  lib/core/src/system/mod.rs
  lib/util/src/lib.rs
  substrate-minimal/subcryptor/Cargo.toml
  substrate-minimal/subcryptor/src/lib.rs
  substrate-minimal/subgrandpa/Cargo.toml
  substrate-minimal/subhasher/Cargo.toml
  substrate-minimal/subhasher/src/lib.rs
  substrate-minimal/submetadatan/Cargo.toml
  substrate-minimal/submetadatan/src/error.rs
  substrate-minimal/subrpcer/Cargo.toml
  substrate-minimal/subrpcer/impl/Cargo.toml
  substrate-minimal/subrpcer/impl/README.md
  substrate-minimal/subrpcer/impl/src/lib.rs
  substrate-minimal/subrpcer/src/author.rs
  substrate-minimal/subrpcer/src/babe.rs
  substrate-minimal/subrpcer/src/chain.rs
  substrate-minimal/subrpcer/src/client/r.rs
  substrate-minimal/subrpcer/src/client/u.rs
  substrate-minimal/subrpcer/src/grandpa.rs
  substrate-minimal/subrpcer/src/lib.rs
  substrate-minimal/subrpcer/src/net.rs
  substrate-minimal/subrpcer/src/offchain.rs
  substrate-minimal/subrpcer/src/payment.rs
  substrate-minimal/subrpcer/src/rpc.rs
  substrate-minimal/subrpcer/src/state.rs
  substrate-minimal/subrpcer/src/system.rs
  substrate-minimal/subruntimer/Cargo.toml
  substrate-minimal/subruntimer/src/lib.rs
  substrate-minimal/substorager/Cargo.toml
  substrate-minimal/substorager/src/lib.rs
  substrate-minimal/subversioner/Cargo.toml
  substrate-minimal/subversioner/src/lib.rs
Labels: Core, Doc

#245 Doc `submetadatan`
  substrate-minimal/submetadatan/Cargo.toml
  substrate-minimal/submetadatan/src/error.rs
  substrate-minimal/submetadatan/src/lib.rs
Labels: Doc

#248 Release `v0.9.0-rc13`
  Cargo.lock
  bin/subalfred/Cargo.toml
  bin/subalfred/src/command/impl/Cargo.toml
  bin/subalfred/src/command/impl/README.md
  bin/subalfred/src/command/impl/debug/Cargo.toml
  lib/core/Cargo.toml
  lib/core/README.md
  lib/util/Cargo.toml
  lib/util/README.md
  substrate-minimal/subcryptor/Cargo.toml
  substrate-minimal/subgrandpa/Cargo.toml
  substrate-minimal/subhasher/Cargo.toml
  substrate-minimal/submetadatan/Cargo.toml
  substrate-minimal/subrpcer/Cargo.toml
  substrate-minimal/subruntimer/Cargo.toml
  substrate-minimal/substorager/Cargo.toml
  substrate-minimal/subversioner/Cargo.toml
Labels: R

#251 More docs
  bin/subalfred/src/command/get/runtime_upgrade_block.rs
  bin/subalfred/src/command/state/mod.rs
  bin/subalfred/src/main.rs
  lib/core/src/cargo/mod.rs
  lib/core/src/error/mod.rs
  lib/core/src/http/mod.rs
  lib/core/src/jsonrpc/http/mod.rs
  lib/core/src/jsonrpc/mod.rs
  lib/core/src/jsonrpc/ws/mod.rs
  lib/core/src/key/mod.rs
  lib/core/src/lib.rs
  lib/core/src/node/mod.rs
  lib/core/src/ss58/mod.rs
  lib/core/src/state/diff.rs
  lib/core/src/state/export.rs
  lib/core/src/state/fork_off.rs
  lib/core/src/state/mod.rs
  lib/core/src/state/override.rs
  lib/core/src/substrate_client/api.rs
  lib/core/src/substrate_client/mod.rs
  lib/core/src/system/mod.rs
Labels: Doc

#252 Update API `get_metadata`
  lib/core/src/state/export.rs
  lib/core/src/substrate_client/api.rs
  lib/core/src/substrate_client/mod.rs
Labels: Core

#253 Finish all core libraries docs
  doc/src/user/cli/state.md
  lib/core/src/check/features/mod.rs
  lib/core/src/check/mod.rs
  lib/core/src/check/runtime.rs
  lib/core/src/http/mod.rs
  lib/core/src/jsonrpc/http/mod.rs
  lib/core/src/jsonrpc/ws/mod.rs
Labels: Doc

#255 Doc all CMDs
  bin/subalfred/src/cli.rs
  bin/subalfred/src/command/check/mod.rs
  bin/subalfred/src/command/check/runtime.rs
  bin/subalfred/src/command/convert/bytes2hex.rs
  bin/subalfred/src/command/convert/bytes_style.rs
  bin/subalfred/src/command/convert/mod.rs
  bin/subalfred/src/command/get/mod.rs
  bin/subalfred/src/command/get/runtime_upgrade_block.rs
  bin/subalfred/src/command/hash.rs
  bin/subalfred/src/command/key.rs
  bin/subalfred/src/command/mod.rs
  bin/subalfred/src/command/state/diff.rs
  bin/subalfred/src/command/state/export.rs
  bin/subalfred/src/command/state/fork_off.rs
  bin/subalfred/src/command/state/override.rs
  bin/subalfred/src/command/storage_key.rs
  bin/subalfred/src/command/workspace/update.rs
  doc/src/user/cli/check.md
  doc/src/user/cli/state.md
Labels: Doc

#256 Anonymous arg
  bin/subalfred/src/command/check/features.rs
  bin/subalfred/src/command/workspace/update.rs
  lib/core/src/cargo/mod.rs
Labels: CLI

#259 Accept block number and hash
  bin/subalfred/src/command/state/export.rs
  lib/core/src/check/features/mod.rs
  lib/core/src/state/diff.rs
  lib/core/src/state/export.rs
  lib/core/src/state/fork_off.rs
  lib/core/src/state/override.rs
  lib/core/src/system/mod.rs
Labels: Core, CLI

#260 Send RPC from CLI
  Cargo.lock
  bin/subalfred/Cargo.toml
  bin/subalfred/src/command/mod.rs
  bin/subalfred/src/command/rpc.rs
Labels: Feat, CLI

#261 Key command support JSON output & beautify its output
  bin/subalfred/src/cli.rs
  bin/subalfred/src/command/key.rs
  bin/subalfred/src/command/mod.rs
  bin/subalfred/src/command/shared.rs
  bin/subalfred/src/command/state/diff.rs
  bin/subalfred/src/command/state/fork_off.rs
  bin/subalfred/src/command/state/override.rs
  lib/core/src/state/mod.rs
Labels: Core, CLI

#262 State insert command & fix API `get_keys_paged`
  bin/subalfred/src/command/check/features.rs
  bin/subalfred/src/command/check/runtime.rs
  bin/subalfred/src/command/key.rs
  bin/subalfred/src/command/rpc.rs
  bin/subalfred/src/command/shared.rs
  bin/subalfred/src/command/state/diff.rs
  bin/subalfred/src/command/state/export.rs
  bin/subalfred/src/command/state/fork_off.rs
  bin/subalfred/src/command/state/insert.rs
  bin/subalfred/src/command/state/mod.rs
  bin/subalfred/src/command/state/override.rs
  bin/subalfred/src/command/workspace/update.rs
  lib/core/src/state/fork_off.rs
  lib/core/src/state/insert.rs
  lib/core/src/state/mod.rs
  lib/core/src/substrate_client/mod.rs
  lib/core/src/system/mod.rs
  substrate-minimal/subrpcer/src/lib.rs
  substrate-minimal/subrpcer/src/state.rs
Labels: Feat, Core, CLI

#263 Eliminate doc warnings
  lib/core/src/key/mod.rs
  lib/core/src/state/insert.rs
  substrate-minimal/subcryptor/src/lib.rs
  substrate-minimal/subruntimer/src/lib.rs
  substrate-minimal/substorager/src/lib.rs
  substrate-minimal/subversioner/src/lib.rs
Labels: Doc

#264 State insert, RPC and JSON output tests
  bin/subalfred/src/command/key.rs
  bin/subalfred/src/command/rpc.rs
  bin/subalfred/src/command/state/insert.rs
  example/cmd/state/src/main.rs
  lib/core/src/state/fork_off.rs
  lib/core/src/state/insert.rs
  lib/core/src/state/mod.rs
  lib/core/src/state/test/mock-chain-spec.json
  lib/core/src/state/test/mod.rs
Labels: TI
